#!/usr/bin/env node
// Typecheck ratchet: the tree does not typecheck yet, so a plain `tsc --noEmit` gate would be
// red on every PR and gate nothing. This compares tsc's per-file error count against a committed
// baseline instead: a file that gets WORSE fails, a file that gets better lowers the bar.
//
// Per-file rather than a single total on purpose — a total lets you fix one error in A, add one
// in B, and sail through. Run with --update to rewrite the baseline after fixing errors.
//
// The debt this exists to retire is inventoried in AGENTS.md → "Tech-debt ledger". When the
// baseline reaches zero, delete this script and gate on `tsc --noEmit` directly.

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const BASELINE_PATH = new URL('../.typecheck-baseline.json', import.meta.url);
const update = process.argv.includes('--update');

// tsc exits non-zero when it reports errors, which is the expected path here.
let output = '';
try {
  output = execFileSync('npx', ['tsc', '--noEmit'], { encoding: 'utf8', stdio: 'pipe' });
} catch (err) {
  output = `${err.stdout ?? ''}${err.stderr ?? ''}`;
  if (!output.trim()) throw err;
}

// Only lines anchored at column 0 are error headers; tsc indents the explanation that follows.
// The lazy group has to backtrack past parentheses in the path itself — Next.js route groups
// (`app/(dashboard)/page.tsx`) contain them, and a greedy-to-first-paren match drops those files
// from the count entirely, which is a ratchet that silently ignores half the app.
const counts = {};
for (const line of output.split('\n')) {
  if (/^\s/.test(line)) continue;
  const match = /^(.+?)\(\d+,\d+\): error TS\d+/.exec(line);
  // `.next/types` is generated by `next build`, so counting it would make the baseline depend on
  // whether you happen to have built. Those errors are real, and the build is what reports them.
  if (match && !match[1].startsWith('.next/')) counts[match[1]] = (counts[match[1]] ?? 0) + 1;
}
const total = Object.values(counts).reduce((a, b) => a + b, 0);

if (update) {
  writeFileSync(BASELINE_PATH, `${JSON.stringify(counts, null, 2)}\n`);
  console.log(`Baseline updated: ${total} error(s) across ${Object.keys(counts).length} file(s).`);
  process.exit(0);
}

if (!existsSync(BASELINE_PATH)) {
  console.error('No .typecheck-baseline.json. Create it with: npm run typecheck:baseline');
  process.exit(1);
}
const baseline = JSON.parse(readFileSync(BASELINE_PATH, 'utf8'));
const baselineTotal = Object.values(baseline).reduce((a, b) => a + b, 0);

const regressions = Object.keys(counts)
  .filter((file) => counts[file] > (baseline[file] ?? 0))
  .map((file) => ({ file, now: counts[file], was: baseline[file] ?? 0 }));

if (regressions.length > 0) {
  console.error('\n✖ Typecheck ratchet: new type errors.\n');
  for (const { file, now, was } of regressions) {
    console.error(`  ${file}: ${was} → ${now}`);
    for (const line of output.split('\n')) {
      if (line.startsWith(`${file}(`)) console.error(`      ${line}`);
    }
  }
  console.error('\nFix them, or — if you deliberately accepted the debt — run:');
  console.error('  npm run typecheck:baseline   (and say why in the PR)\n');
  process.exit(1);
}

if (total < baselineTotal) {
  console.log(`✔ Typecheck ratchet: ${baselineTotal} → ${total} error(s). Progress!`);
  console.log('  Lock it in with: npm run typecheck:baseline');
  process.exit(0);
}

console.log(
  total === 0
    ? '✔ Typecheck clean. Retire this ratchet and gate on `tsc --noEmit` directly.'
    : `✔ Typecheck ratchet held at ${total} known error(s). No regressions.`,
);
